[package]
name = "tincan"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"

[dependencies]
cfg-if = "1.0.1"

[features]
std = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_unstable"]
